### ISSUE TITLE
issue: zustand setAuth 이슈

### ISSUE THREAD

**Issue by jake920220** [yuna-c/outsourcing#30]
1. 

https://github.com/yuna-c/outsourcing/blob/404cc14be3197f55de6ef7168e195eadf3c4ef2e/src/components/pages/SignUp.jsx#L45-L48

register 이후 해당 응답값(response)에는 데이터들이 들어있지 않습니다.
그래서 undefined들이 zustand store에 set 되고 있었습니다.

2.

https://github.com/yuna-c/outsourcing/blob/404cc14be3197f55de6ef7168e195eadf3c4ef2e/src/core/stores/useAuthStore.js#L21-L31

store에서 setAuth를 해줄 때 인자가 객체 형태가 아니라서 순서가 강제됩니다.
(accessToken, nickname, userId, avatar) -> ({accessToken, nickname, userId, avatar}) 이렇게 refactoring이 필요해 보입니다.

**Comment by yuna-c** [comment]
이렇게하면 깃허브로그인 기본프로필이랑 닉네임 안떠서 수정해놨어툐
