### ISSUE TITLE
issue: mypage 디자인 이슈 

### ISSUE THREAD

**Issue by yuna-c** [yuna-c/outsourcing#57]
https://github.com/yuna-c/outsourcing/blob/308c8ada7f8abaeca90f6e6711fc753ee1682d56/src/components/pages/MyPage.jsx#L74-L78

요 탭 부분의 선들이 너무 튀어 톤과 살짝 맞지 않아 보이는 것 같습니다! 

![image](https://github.com/user-attachments/assets/78c08906-a648-41dd-af21-b006698ebec3)
![image](https://github.com/user-attachments/assets/9e5a7e99-005e-4f6f-ba7b-d9dd14a31ae1)
![image](https://github.com/user-attachments/assets/99a23a7a-59ac-4047-94af-06746d01f63d)

수정 부탁드리겠습니다!

**Comment by wldndnwl** [comment]
수정했습니다 :3
