### ISSUE TITLE
issue: youtube 이슈 

### ISSUE THREAD

**Issue by yuna-c** [yuna-c/outsourcing#58]
반응형 작업할 때 회수를 다 써버려서 저 데이터가 있는 태그에 수정하지 못하고 따로 목데이터를 만들어 수정하였습니다
다시 횟수가 돌아오면 수정 부탁드립니다.

그리고 유튜브 데이터는 9개 정도 들어갔으면 좋겠어요

https://github.com/yuna-c/outsourcing/blob/308c8ada7f8abaeca90f6e6711fc753ee1682d56/src/components/common/main/Youtube.jsx#L1-L119

**Comment by wldud7788** [comment]
넵 Youtube API의 하루 할당량 돌아오면 수정하겠습니다.
유트브 9개 정도 들어갈 수있도록 수정해두겠습니다.

search list API는 1회 당 100 이므로 하루 최대 100번까지만 검색 기능 사용 가능하고, 

제 코드가 현재 시간을 가져와서 분이 바뀔때마다 그 시간에 맞는 약국들을 뿌려주는거라서
리렌더링 될때마다 사용될거고, 
100이면 금방 소진될 것 같은데 

제가 파악한게 맞는지랑, 
어떻게 해야할지도 같이 확인해보겠습니다.

**Comment by yuna-c** [comment]
이거 데이터만 9개 뿌리면 돼요!! Ui작업은 다 해놨어요

**Comment by yuna-c** [comment]
#71 해결완료
